insert  into `fa_auth_rule`(`id`,`type`,`pid`,`name`,`title`,`icon`,`url`,`condition`,`remark`,`ismenu`,`menutype`,`extend`,`py`,`pinyin`,`createtime`,`updatetime`,`weigh`,`status`) values 
(433,'file',0,'csmipr','CSM 知识产权管理系统','fa fa-list','','','',1,'addtabs','','Czscqglxt','CSMzhishichanquanguanlixitong',1720067844,1720429160,0,'normal'),
(434,'file',468,'csmipr/shangbiao','商标','fa fa-circle-o','','','',1,'addtabs','','sb','shangbiao',1720067844,1720429224,0,'normal'),
(435,'file',434,'csmipr/shangbiao/import','Import','fa fa-circle-o','','','',0,NULL,'','dr','daoru',1720067845,1720427939,0,'normal'),
(436,'file',434,'csmipr/shangbiao/index','查看','fa fa-circle-o','','','',0,NULL,'','zk','zhakan',1720067845,1720427939,0,'normal'),
(437,'file',434,'csmipr/shangbiao/add','添加','fa fa-circle-o','','','',0,NULL,'','tj','tianjia',1720067845,1720427940,0,'normal'),
(438,'file',434,'csmipr/shangbiao/edit','编辑','fa fa-circle-o','','','',0,NULL,'','bj','bianji',1720067845,1720427940,0,'normal'),
(439,'file',434,'csmipr/shangbiao/del','删除','fa fa-circle-o','','','',0,NULL,'','sc','shanchu',1720067845,1720427940,0,'normal'),
(440,'file',434,'csmipr/shangbiao/multi','批量更新','fa fa-circle-o','','','',0,NULL,'','plgx','pilianggengxin',1720067845,1720427940,0,'normal'),
(441,'file',469,'csmipr/shangbiao_fenlei','商标的分类','fa fa-circle-o','','','',1,'addtabs','','sbdfl','shangbiaodifenlei',1720074974,1720429285,0,'normal'),
(442,'file',441,'csmipr/shangbiao_fenlei/import','Import','fa fa-circle-o','','','',0,NULL,'','dr','daoru',1720074975,1720076059,0,'normal'),
(443,'file',441,'csmipr/shangbiao_fenlei/index','查看','fa fa-circle-o','','','',0,NULL,'','zk','zhakan',1720074975,1720076059,0,'normal'),
(444,'file',441,'csmipr/shangbiao_fenlei/add','添加','fa fa-circle-o','','','',0,NULL,'','tj','tianjia',1720074975,1720076059,0,'normal'),
(445,'file',441,'csmipr/shangbiao_fenlei/edit','编辑','fa fa-circle-o','','','',0,NULL,'','bj','bianji',1720074975,1720076059,0,'normal'),
(446,'file',441,'csmipr/shangbiao_fenlei/del','删除','fa fa-circle-o','','','',0,NULL,'','sc','shanchu',1720074975,1720076059,0,'normal'),
(447,'file',441,'csmipr/shangbiao_fenlei/multi','批量更新','fa fa-circle-o','','','',0,NULL,'','plgx','pilianggengxin',1720074975,1720076059,0,'normal'),
(448,'file',469,'csmipr/shangbiao_zhuangtai','商标的状态','fa fa-circle-o','','','',1,'addtabs','','sbdzt','shangbiaodizhuangtai',1720076072,1720429296,0,'normal'),
(449,'file',448,'csmipr/shangbiao_zhuangtai/import','Import','fa fa-circle-o','','','',0,NULL,'','dr','daoru',1720076073,1720076073,0,'normal'),
(450,'file',448,'csmipr/shangbiao_zhuangtai/index','查看','fa fa-circle-o','','','',0,NULL,'','zk','zhakan',1720076073,1720076073,0,'normal'),
(451,'file',448,'csmipr/shangbiao_zhuangtai/add','添加','fa fa-circle-o','','','',0,NULL,'','tj','tianjia',1720076073,1720076073,0,'normal'),
(452,'file',448,'csmipr/shangbiao_zhuangtai/edit','编辑','fa fa-circle-o','','','',0,NULL,'','bj','bianji',1720076073,1720076073,0,'normal'),
(453,'file',448,'csmipr/shangbiao_zhuangtai/del','删除','fa fa-circle-o','','','',0,NULL,'','sc','shanchu',1720076073,1720076073,0,'normal'),
(454,'file',448,'csmipr/shangbiao_zhuangtai/multi','批量更新','fa fa-circle-o','','','',0,NULL,'','plgx','pilianggengxin',1720076073,1720076073,0,'normal'),
(468,'file',433,'csmipr/mulu_shangbiao','商标管理','fa fa-circle-o','','','',1,'addtabs','','sbgl','shangbiaoguanli',1720429199,1720429275,0,'normal'),
(469,'file',433,'csmipr/mulu_jichu','基础数据','fa fa-circle-o','','','',1,'addtabs','','jcsj','jichushuju',1720429263,1720429263,0,'normal'),
(470,'file',433,'csmipr/company','公司法体管理','fa fa-circle-o\r','','','',1,NULL,'','gsftgl','gongsifatiguanli',1723107170,1723107170,0,'normal'),
(471,'file',470,'csmipr/company/index','查看','fa fa-circle-o','','','',0,NULL,'','zk','zhakan',1723107171,1723107171,0,'normal'),
(472,'file',470,'csmipr/company/add','添加','fa fa-circle-o','','','',0,NULL,'','tj','tianjia',1723107171,1723107171,0,'normal'),
(473,'file',470,'csmipr/company/edit','编辑','fa fa-circle-o','','','',0,NULL,'','bj','bianji',1723107171,1723107171,0,'normal'),
(474,'file',470,'csmipr/company/del','删除','fa fa-circle-o','','','',0,NULL,'','sc','shanchu',1723107171,1723107171,0,'normal'),
(475,'file',470,'csmipr/company/multi','批量更新','fa fa-circle-o','','','',0,NULL,'','plgx','pilianggengxin',1723107171,1723107171,0,'normal');

CREATE TABLE `fa_csmipr_shangbiao` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `csmipr_company_id` int(11) DEFAULT NULL COMMENT '公司法体',
  `name` varchar(100) DEFAULT '' COMMENT '名称',
  `tuan_image` varchar(100) DEFAULT '' COMMENT '图案',
  `fenlei_id` int(11) DEFAULT NULL COMMENT '国际分类',
  `zhucehao` varchar(255) DEFAULT NULL COMMENT '注册号',
  `zhuangtai_id` int(11) DEFAULT NULL COMMENT '商标状态',
  `isgongyu` enum('Y','N') DEFAULT NULL COMMENT '是否共有商标:Y=是,N=否',
  `leixing` varchar(255) DEFAULT NULL COMMENT '商标类型',
  `youxianquan_date` date DEFAULT NULL COMMENT '优先权日期',
  `guojizhuce_date` date DEFAULT NULL COMMENT '国际注册日期',
  `houqizhiding_date` date DEFAULT NULL COMMENT '后期指定日期',
  `leisiqun` varchar(255) DEFAULT NULL COMMENT '类似群',
  `xingshi` varchar(255) DEFAULT NULL COMMENT '商标形式',
  `shenqing_date` date DEFAULT NULL COMMENT '商标申请日期',
  `zhuanyongquan_begindate` date DEFAULT NULL COMMENT '专用权期限(开始)',
  `zhuanyongquan_enddate` date DEFAULT NULL COMMENT '专用权期限(截止)',
  `shenqingren` varchar(255) DEFAULT NULL COMMENT '申请人',
  `en_shenqingren` varchar(255) DEFAULT NULL COMMENT '申请人(英文)',
  `shenqingrendizhi` varchar(255) DEFAULT NULL COMMENT '申请人地址',
  `en_shenqingrendizhi` varchar(255) DEFAULT NULL COMMENT '申请人英文地址',
  `banlijigou` varchar(255) DEFAULT NULL COMMENT '办理机构',
  `shangbiaoshangpingfuwu` varchar(1000) DEFAULT NULL COMMENT '商品/服务项目',
  `chushengonggaoqihao` varchar(255) DEFAULT NULL COMMENT '初审公告期号',
  `chushengonggao_date` date DEFAULT NULL COMMENT '初审公告日期',
  `zhidingyanse` varchar(255) DEFAULT NULL COMMENT '指定颜色',
  `zhucegonggaoqihao` varchar(255) DEFAULT NULL COMMENT '注册公告期号',
  `zhucegonggao_date` date DEFAULT NULL COMMENT '注册公告日期',
  `hastuan` enum('Y','N') DEFAULT NULL COMMENT '是否有图案:Y=有,N=无',
  `liuchegnzhuagntai_id` int(11) DEFAULT NULL COMMENT '流程状态',
  `desc` text COMMENT '备注',
  `from_source` varchar(100) DEFAULT NULL COMMENT '来源系统',
  `from_uuid` varchar(100) DEFAULT NULL COMMENT '来源UUID',
  `user_id` int(10) DEFAULT '0' COMMENT '会员ID',
  `admin_id` int(10) DEFAULT '0' COMMENT '管理员ID',
  `createtime` bigint(16) DEFAULT NULL COMMENT '创建时间',
  `updatetime` bigint(16) DEFAULT NULL COMMENT '更新时间',
  `weigh` int(10) DEFAULT '0' COMMENT '权重',
  `status` enum('normal','hidden') DEFAULT 'normal' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COMMENT='商标';

/*Data for the table `fa_csmipr_shangbiao` */


CREATE TABLE `fa_csmipr_shangbiao_fenlei` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `uuid` varchar(100) DEFAULT '' COMMENT '编号',
  `name` varchar(100) DEFAULT '' COMMENT '名称',
  `desc` text COMMENT '备注',
  `from_source` varchar(100) DEFAULT NULL COMMENT '来源系统',
  `from_uuid` varchar(100) DEFAULT NULL COMMENT '来源UUID',
  `user_id` int(10) DEFAULT '0' COMMENT '会员ID',
  `admin_id` int(10) DEFAULT '0' COMMENT '管理员ID',
  `createtime` bigint(16) DEFAULT NULL COMMENT '创建时间',
  `updatetime` bigint(16) DEFAULT NULL COMMENT '更新时间',
  `weigh` int(10) DEFAULT '0' COMMENT '权重',
  `status` enum('normal','hidden') DEFAULT 'normal' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb4 COMMENT='商标的分类';

/*Data for the table `fa_csmipr_shangbiao_fenlei` */

insert  into `fa_csmipr_shangbiao_fenlei`(`id`,`uuid`,`name`,`desc`,`from_source`,`from_uuid`,`user_id`,`admin_id`,`createtime`,`updatetime`,`weigh`,`status`) values 
(2,'1','第一类 化学原料',NULL,NULL,NULL,0,0,NULL,NULL,1,'normal'),
(3,'2','第二类 颜料油漆',NULL,NULL,NULL,0,0,NULL,NULL,2,'normal'),
(4,'3','第三类 日化用品',NULL,NULL,NULL,0,0,NULL,NULL,3,'normal'),
(5,'4','第四类 燃料油脂',NULL,NULL,NULL,0,0,NULL,NULL,4,'normal'),
(6,'5','第五类 医药',NULL,NULL,NULL,0,0,NULL,NULL,5,'normal'),
(7,'6','第六类 金属材料',NULL,NULL,NULL,0,0,NULL,NULL,6,'normal'),
(8,'7','第七类 机械设备',NULL,NULL,NULL,0,0,NULL,NULL,7,'normal'),
(9,'8','第八类 手工器械',NULL,NULL,NULL,0,0,NULL,NULL,8,'normal'),
(10,'9','第九类 科学仪器',NULL,NULL,NULL,0,0,NULL,NULL,9,'normal'),
(11,'10','第十类 医疗器械',NULL,NULL,NULL,0,0,NULL,NULL,10,'normal'),
(12,'11','第十一类 灯具空调',NULL,NULL,NULL,0,0,NULL,NULL,11,'normal'),
(13,'12','第十二类 运输工具',NULL,NULL,NULL,0,0,NULL,NULL,12,'normal'),
(14,'13','第十三类 军火烟火',NULL,NULL,NULL,0,0,NULL,NULL,13,'normal'),
(15,'14','第十四类 珠宝钟表',NULL,NULL,NULL,0,0,NULL,NULL,14,'normal'),
(16,'15','第十五类 乐器',NULL,NULL,NULL,0,0,NULL,NULL,15,'normal'),
(17,'16','第十六类 办公品',NULL,NULL,NULL,0,0,NULL,NULL,16,'normal'),
(18,'17','第十七类 橡胶制品',NULL,NULL,NULL,0,0,NULL,NULL,17,'normal'),
(19,'18','第十八类 皮革皮具',NULL,NULL,NULL,0,0,NULL,NULL,18,'normal'),
(20,'19','第十九类 建筑材料',NULL,NULL,NULL,0,0,NULL,NULL,19,'normal'),
(21,'20','第二十类 家具',NULL,NULL,NULL,0,0,NULL,NULL,20,'normal'),
(22,'21','第二十一类 厨房洁具',NULL,NULL,NULL,0,0,NULL,NULL,21,'normal'),
(23,'22','第二十二类 绳网袋篷',NULL,NULL,NULL,0,0,NULL,NULL,22,'normal'),
(24,'23','第二十三类 纱线丝',NULL,NULL,NULL,0,0,NULL,NULL,23,'normal'),
(25,'24','第二十四类 布料床单',NULL,NULL,NULL,0,0,NULL,NULL,24,'normal'),
(26,'25','第二十五类 服装鞋帽',NULL,NULL,NULL,0,0,NULL,NULL,25,'normal'),
(27,'26','第二十六类 钮扣拉链',NULL,NULL,NULL,0,0,NULL,NULL,26,'normal'),
(28,'27','第二十七类 地毯席垫',NULL,NULL,NULL,0,0,NULL,NULL,27,'normal'),
(29,'28','第二十八类 键身器材',NULL,NULL,NULL,0,0,NULL,NULL,28,'normal'),
(30,'29','第二十九类 食品',NULL,NULL,NULL,0,0,NULL,NULL,29,'normal'),
(31,'30','第三十类 方便食品',NULL,NULL,NULL,0,0,NULL,NULL,30,'normal'),
(32,'31','第三十一类 饲料种籽',NULL,NULL,NULL,0,0,NULL,NULL,31,'normal'),
(33,'32','第三十二类 啤酒饮料',NULL,NULL,NULL,0,0,NULL,NULL,32,'normal'),
(34,'33','第三十三类 酒',NULL,NULL,NULL,0,0,NULL,NULL,33,'normal'),
(35,'34','第三十四类 烟草烟具',NULL,NULL,NULL,0,0,NULL,NULL,34,'normal'),
(36,'35','第三十五类 广告销售',NULL,NULL,NULL,0,0,NULL,NULL,35,'normal'),
(37,'36','第三十六类 金融物管',NULL,NULL,NULL,0,0,NULL,NULL,36,'normal'),
(38,'37','第三十七类 建筑修理',NULL,NULL,NULL,0,0,NULL,NULL,37,'normal'),
(39,'38','第三十八类 通讯服务',NULL,NULL,NULL,0,0,NULL,NULL,38,'normal'),
(40,'39','第三十九类 运输贮藏',NULL,NULL,NULL,0,0,NULL,NULL,39,'normal'),
(41,'40','第四十类 材料加工',NULL,NULL,NULL,0,0,NULL,NULL,40,'normal'),
(42,'41','第四十一类 教育娱乐',NULL,NULL,NULL,0,0,NULL,NULL,41,'normal'),
(43,'42','第四十二类 设计研究',NULL,NULL,NULL,0,0,NULL,NULL,42,'normal'),
(44,'43','第四十三类 餐饮住宿',NULL,NULL,NULL,0,0,NULL,NULL,43,'normal'),
(45,'44','第四十四类 医疗园艺',NULL,NULL,NULL,0,0,NULL,NULL,44,'normal'),
(46,'45','第四十五类 社会法律',NULL,NULL,NULL,0,0,NULL,NULL,45,'normal');

CREATE TABLE `fa_csmipr_shangbiao_liuchegnzhuagntai` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `uuid` varchar(100) DEFAULT '' COMMENT '编号',
  `name` varchar(100) DEFAULT '' COMMENT '状态名称',
  `desc` text COMMENT '备注',
  `from_souce` varchar(100) DEFAULT '' COMMENT '来源系统',
  `from_uuid` varchar(100) DEFAULT '' COMMENT '来源UUID',
  `user_id` int(10) DEFAULT '0' COMMENT '会员ID',
  `admin_id` int(10) DEFAULT '0' COMMENT '管理员ID',
  `createtime` bigint(16) DEFAULT NULL COMMENT '创建时间',
  `updatetime` bigint(16) DEFAULT NULL COMMENT '更新时间',
  `weigh` int(10) DEFAULT '0' COMMENT '权重',
  `status` enum('normal','hidden') DEFAULT 'normal' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='商标的流程状态';

/*Data for the table `fa_csmipr_shangbiao_liuchegnzhuagntai` */

CREATE TABLE `fa_csmipr_shangbiao_zhuangtai` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `uuid` varchar(100) DEFAULT '' COMMENT '编号',
  `name` varchar(100) DEFAULT '' COMMENT '名称',
  `desc` text COMMENT '备注',
  `from_source` varchar(100) DEFAULT NULL COMMENT '来源系统',
  `from_uuid` varchar(100) DEFAULT NULL COMMENT '来源UUID',
  `user_id` int(10) DEFAULT '0' COMMENT '会员ID',
  `admin_id` int(10) DEFAULT '0' COMMENT '管理员ID',
  `createtime` bigint(16) DEFAULT NULL COMMENT '创建时间',
  `updatetime` bigint(16) DEFAULT NULL COMMENT '更新时间',
  `weigh` int(10) DEFAULT '0' COMMENT '权重',
  `status` enum('normal','hidden') DEFAULT 'normal' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COMMENT='商标的状态';

/*Data for the table `fa_csmipr_shangbiao_zhuangtai` */

insert  into `fa_csmipr_shangbiao_zhuangtai`(`id`,`uuid`,`name`,`desc`,`from_source`,`from_uuid`,`user_id`,`admin_id`,`createtime`,`updatetime`,`weigh`,`status`) values 
(2,'2','已注册',NULL,NULL,NULL,0,0,NULL,NULL,0,'normal'),
(3,'3','注册申请中',NULL,NULL,NULL,0,0,NULL,NULL,0,'normal'),
(4,'4','商标无效',NULL,NULL,NULL,0,0,NULL,NULL,0,'normal'),
(5,'5','无效宣告完成',NULL,NULL,NULL,0,0,NULL,NULL,0,'normal'),
(6,'6','驳回待复审',NULL,NULL,NULL,0,0,NULL,NULL,0,'normal'),
(7,'7','驳回复审中',NULL,NULL,NULL,0,0,NULL,NULL,0,'normal');

CREATE TABLE `fa_csmipr_shangbiaozhuceliucheng` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `shangbiao_id` int(11) DEFAULT NULL COMMENT '商标',
  `uuid` varchar(100) DEFAULT '' COMMENT '编号',
  `name` varchar(100) DEFAULT '' COMMENT '流程步骤',
  `zhuce_date` date DEFAULT NULL COMMENT '流程步骤日期',
  `desc` text COMMENT '备注',
  `from_source` varchar(100) DEFAULT NULL COMMENT '来源系统',
  `from_uuid` varchar(100) DEFAULT NULL COMMENT '来源UUID',
  `user_id` int(10) DEFAULT '0' COMMENT '会员ID',
  `admin_id` int(10) DEFAULT '0' COMMENT '管理员ID',
  `createtime` bigint(16) DEFAULT NULL COMMENT '创建时间',
  `updatetime` bigint(16) DEFAULT NULL COMMENT '更新时间',
  `weigh` int(10) DEFAULT '0' COMMENT '权重',
  `status` enum('normal','hidden') DEFAULT 'normal' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='商标注册流程';

CREATE TABLE `fa_csmipr_company` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` varchar(100) DEFAULT '' COMMENT '公司名',
  `org_code` varchar(100) DEFAULT '' COMMENT '统一组织机构代码',
  `desc` text COMMENT '描述',
  `admin_id` int(10) DEFAULT '0' COMMENT '管理员ID',
  `createtime` bigint(16) DEFAULT NULL COMMENT '创建时间',
  `updatetime` bigint(16) DEFAULT NULL COMMENT '更新时间',
  `weigh` int(10) DEFAULT '0' COMMENT '权重',
  `status` enum('normal','hidden') DEFAULT 'normal' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COMMENT='公司法体表';